export type NhlSearchPlayer = {
	playerId: string;
	name: string;
	positionCode: string;
	teamId: string;
	teamAbbrev: string;
	lastTeamId: string;
	lastTeamAbbrev: string;
	lastSeasonId: string;
	sweaterNumber: number;
	active: true;
	height: string;
	heightInInches: number;
	heightInCentimeters: number;
	weightInPounds: number;
	weightInKilograms: number;
	birthCity: string;
	birthStateProvince: string | null;
	birthCountry: string;
};
